[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "volcanology-course"
version = "0.1.0"
dependencies = [
    # Core packages shared by all notebooks (can be empty)
]

[tool.setuptools.packages.find]
include = ["course*"]

[project.optional-dependencies]
# Dependencies for Data Analysis
data = [
    "pandas",
    "numpy",
    "matplotlib",
]

# Dependencies for Machine Learning / Deep Learning
ml = [
    "torch",
    "torchinfo"
]

# Dependencies for Maps
maps = [
    "cartopy",
    "xarray",
    "netCDF4"
]
